services:
  jekyll:
    build:
      context: ..
      dockerfile: dev/Dockerfile
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - ../..:/project
      - /home/danfreudend/hytale-server-container/docs/vendor/bundle:/usr/local/bundle/ruby/3.3.0
    working_dir: /project/docs
    command: bundle exec jekyll serve --host 0.0.0.0 --livereload --force_polling
